# -*- coding: utf-8 -*-
"""Formative 3 - Probability Distributions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GYNRH4g-mY7UuG_Q9DICR0_LVR7lW4B_
"""

import numpy as np
import pandas as pd

"""**Loading the data**"""

df = pd.read_csv("/content/sample_data/GaltonFamilies.csv")

print(df.head())

father_heights = df["father"].values
child_heights = df["childHeight"].values

heights = np.concatenate([father_heights, child_heights])
heights

"""**Initializing the parameters**"""

# mean
mu1 = np.percentile(heights, 25)
mu2 = np.percentile(heights, 75)
# variance
sigma1 = np.var(heights)
sigma2 = np.var(heights)
# coeffieciency Imagine it is 50 50
pi1 = 0.5
pi2 = 0.5

"""**Gaussian Function**"""

def gaussian(x, mu, sigma):
    return (
        1 / np.sqrt(2 * np.pi * sigma)
    ) * np.exp(
        -((x - mu) ** 2) / (2 * sigma)
    )

#Testing the gaussian
print(gaussian(70, 70, 4))
print(gaussian(90, 70, 4))

"""**E-Step**"""

def e_step(data, mu1, mu2, sigma1, sigma2, pi1, pi2):
  N1 = gaussian(data, mu1, sigma1)
  N2 = gaussian(data, mu2, sigma2)
  r1 = ( pi1 * N1 ) / ( pi1 * N1 + pi2 * N2 )
  r2 = ( pi2 * N2 ) / ( pi1 * N1 + pi2 * N2 )

  return r1, r2

"""**M-Step**"""

def m_step(data, r1, r2):
  mu1 = np.sum(r1 * data) / np.sum(r1)
  mu2 = np.sum(r2 * data) / np.sum(r2)
  #Update the variance
  sigma1 = np.sum( r1 * (data - mu1) ** 2 ) / np.sum(r1)
  sigma2 = np.sum( r2 * (data - mu2) ** 2 ) / np.sum(r2)
  #Update the coefficiency
  pi1 = np.mean(r1)
  pi2 = np.mean(r2)

  return mu1, mu2, sigma1, sigma2, pi1, pi2

"""**Log Likelihood**"""

def log_likelihood(data, mu1, mu2, sigma1, sigma2, pi1, pi2):
    return np.sum(
        np.log(
            pi1 * gaussian(data, mu1, sigma1)
            +
            pi2 * gaussian(data, mu2, sigma2)
        )
    )

"""# **Print Initial State**"""

print(f"{'Iteration':>6} | {'μ1 (Children)':>12} | {'μ2 (Father)':>12} | {'σ1²':>8} | {'σ2²':>8} | {'π1':>8} | {'π2':>8} | {'Log-Likelihood':>15}")
#first iteration
print(f"{0:6d} | {mu1:12.4f} | {mu2:12.4f} | {sigma1:8.4f} | {sigma2:8.4f} | {pi1:8.4f} | {pi2:8.4f} | {log_likelihood( heights, mu1, mu2, sigma1, sigma2, pi1, pi2 ):15.4f}")
#EM Loop
num_iterations = 5
for iteration in range(1, num_iterations + 1):
  #E-Step
  r1, r2 = e_step(heights, mu1, mu2, sigma1, sigma2, pi1, pi2)
  #M-Step
  mu1, mu2, sigma1, sigma2, pi1, pi2 = m_step( heights, r1, r2)
  #Log-Likelihood
  ll = log_likelihood( heights, mu1, mu2, sigma1, sigma2, pi1, pi2 )
  print(f"{iteration:6d} | {mu1:12.4f} | {mu2:12.4f} | {sigma1:8.4f} | {sigma2:8.4f} | {pi1:8.4f} | {pi2:8.4f} | {ll:15.4f}")

"""**Classification Function**"""

def classify_height( height, mu1, mu2, sigma1, sigma2, pi1, pi2 ):
  N1 = gaussian( height, mu1, sigma1 )
  N2 = gaussian( height, mu2, sigma2 )
  p1 = ( pi1 * N1 ) / ( pi1 * N1 + pi2 * N2 )
  p2 = ( pi2 * N2 ) / ( pi1 * N1 + pi2 * N2 )
  return p1, p2

"""**Testing Height**"""

test_height = float( input("\nEnter a height: ") )
p1, p2 = classify_height( test_height, mu1, mu2, sigma1, sigma2, pi1, pi2 )
print("\nPosterior Probabilities")
print(f"Probability being kid:{ p1* 100:.2f}%")
print(f"Probability being Father:{p2* 100:.2f}%")